version: "3"
services:
  thrive-mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    hostname: localhost
    network_mode: "host"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  thrive-eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8089:8089

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - thrive-eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090
  user-service:
    container_name: user-service
    build: user-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8032:8032
    depends_on:
      - thrive-eureka-server
    restart: always

  authentication-service:
    container_name: authentication-service
    build: authentication-service/
    hostname: localhost
    network_mode: "host"
    depends_on:
      - thrive-eureka-server
    ports:
      - 8022:8022
    restart: always

  booking-service:
    container_name: booking-service
    build: booking-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8024:8024
    depends_on:
      - thrive-eureka-server
    restart: always

  sports-arena-details-service:
    container_name: sports-arena-details-service
    build: sports-arena-details-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8030:8030
    depends_on:
      - thrive-eureka-server
    restart: always
    environment:
      SERVER_PORT: 8030
      SPRING_DATA_MONGODB_URI: mongodb+srv://pranav:pranav@cluster0.vhcapvq.mongodb.net/
      SPRING_DATA_MONGODB_DATABASE: groundDB
      SPRING_RABBITMQ_VIRTUAL_HOST: ixesbrvr
      SPRING_RABBITMQ_HOST: puffin-01.rmq2.cloudamqp.com
      SPRING_RABBITMQ_PASSWORD: LLn41jUma2PgP9xOQ0J2tIMxlyfQEG2w
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ixesbrvr
      THRIVE_STORAGE_CLOUD_NAME: drspbfzg3
      THRIVE_STORAGE_API_KEY: 525224343455475
      THRIVE_STORAGE_API_SECRET: qyWFNTyKnDFUbxzUwpSgheswWX4
      THRIVE_NOTIFICATION_EXCHANGE: thrive-exchange
      THRIVE_NOTIFICATION_ROUTING_KEY: thrive-routing-key

  payment-service:
    container_name: payment-service
    build: payment-service/
    hostname: localhost
    network_mode: "host"
    depends_on:
      - thrive-eureka-server
    ports:
      - 8028:8028
    restart: always



  product-webapp-service:
    build: product-webapp-service/
    image: product-webapp-service
    restart: always
    container_name: product-webapp-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8015:8015

  notification-service:
    build:   notification-service/
    restart: always
    container_name:   notification-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8026:8026
  weather-service:
    build: weather-service/
    restart: always
    container_name:   weather-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8034:8034




