#Change port in future
server:
  port: 8090

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: ARENA-DETAIL-SERVICE
          #          uri: lb://ARENA-DETAIL-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/**
        - id: AUTHENTICATION-SERVICE
#          uri: lb://AUTHENTICATION-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: BOOKING-SERVICE
          #          uri: lb://BOOKING-SERVICE
          uri: http://localhost:8012
          predicates:
            - Path=/api/v1/booking/**
        - id: PAYMENT-SERVICE
          #          uri: lb://PAYMENT-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/thrive/payments/**
        - id: USER-SERVICE
          #          uri: lb://USER-SERVICE
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/thrive/user/**


eureka:
  instance:
    #    host: thrive-eureka-env.eba-eyupkwps.eu-north-1.elasticbeanstalk.com
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8089/eureka
