#Change port in future
server:
  port: 8099

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ARENA-DETAIL-SERVICE
          uri: lb://ARENA-DETAIL-SERVICE
          predicates:
            - Path=/api/v1/arena/details/**

eureka:
  instance:
#    host: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8089/eureka
