#Change port in future
server:
  port: 8090

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: SPORTS-ARENA-DETAIL-SERVICE
##          uri: lb://SPORTS-ARENA-DETAIL-SERVICE
#          uri: http://localhost:8030
#          predicates:
#            - Path=/api/v1/arena/**
#
#        - id: SPORTS-ARENA-DETAIL-SERVICE
#          #          uri: lb://SPORTS-ARENA-DETAIL-SERVICE
#          uri: http://localhost:8030
#          predicates:
#            - Path=/api/v1/region/**
#        - id: AUTHENTICATION-SERVICE
##          uri: lb://AUTHENTICATION-SERVICE
#          uri: http://localhost:8022
#          predicates:
#            - Path=/api/v1/auth/**
#
#        - id: BOOKING-SERVICE
##          uri: lb://BOOKING-SERVICE
#          uri: http://localhost:8024
#          predicates:
#            - Path=/api/v1/booking/**
#        - id: PAYMENT-SERVICE
##          uri: lb://PAYMENT-SERVICE
#          uri: http://localhost:8028
#          predicates:
#            - Path=/api/v1/thrive/payments/**
#        - id: USER-SERVICE
##          uri: lb://USER-SERVICE
#          uri: http://localhost:8032
#          predicates:
#            - Path=/api/v1/thrive/user/**
#
#        - id: PRODUCT-WEBAPP-SERVICE
##          uri: lb://PRODUCT-WEBAPP-SERVICE
#          uri: http://localhost:8015
#          predicates:
#            - Path=/**


eureka:
  instance:
    #    host: thrive-eureka-env.eba-eyupkwps.eu-north-1.elasticbeanstalk.com
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8089/eureka/
