FROM openjdk:11
WORKDIR user/lib
EXPOSE 8030
ADD ./target/sports-arena-details-service-0.0.1-SNAPSHOT.jar /user/lib/sports-arena-details-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","sports-arena-details-service-0.0.1-SNAPSHOT.jar"]


