FROM openjdk:17
WORKDIR /usr/lib/app
ADD ./target/authentication-service-0.0.1-SNAPSHOT.jar /usr/lib/app/authentication-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","authentication-service-0.0.1-SNAPSHOT.jar" ]
